### ISSUE TITLE
About scalingFactor

### ISSUE THREAD

**Issue by jasontangxf** [nphoff/saxpy#4]
Hi,

I read the original paper about SAX and get really confused about the meaning of scalingFactor in your implementation.  

I get a use case in which there are 7 template signals that are not in the same length and  the signal being compared is also in the different length. When comparing that signal with templates, it seems that scalingFactor does not affect the final result, which is the template with minimum distance. 

Would you please give some hints about how to use the library for my case? 

Thanks in advance

**Comment by nphoff** [comment]
Hi,

Could you give an example?

Thanks
