### ISSUE TITLE
Missing return in normalize

### ISSUE THREAD

**Issue by jeffcbecker** [nphoff/saxpy#7]
Hi. In the normalize function,  if np.nanstd(X) < self.eps: the code goes and constructs the list res with 0's and NaN's as appropriate. However, it doesn't return res, but falls through to the computation which should only be done if np.nanstd(X) >= self.eps. I think this is a bug. I can submit a patch if you like, but it's so simple, I figured it should just be added. Thanks.

Jeff Becker (jeff.c.becker@nasa.gov)

**Comment by nphoff** [comment]
Oh wow. You're so right. Great catch! I'll update it now.

**Comment by nphoff** [comment]
Thanks, it has been updated.
